### PR TITLE
Update Downloads page with link to ppc64le / aarch64 iso

### PR DESCRIPTION
**Pull request by runlevel5**
Before:

before

After:

after

### CODE REVIEW

**Comment by sharkcz** [comment]
When doing it, please add also aarch64 image, so we are complete then. Should be matter of simply `s/ppc64le/aarch64/` in the URLs.

**Comment by runlevel5** [comment]
> When doing it, please add also aarch64 image, so we are complete then. Should be matter of simply s/ppc64le/aarch64/ in the URLs. Silverblue for aarch64 has the same status as for ppc64le.

I could not find any ISO for aarch64 in the `https://download.fedoraproject.org/pub/fedora-secondary/releases/32/Silverblue/`. I guess we could go with the https://kojipkgs.fedoraproject.org/compose/32/latest-Fedora-32/compose/Silverblue/aarch64/iso/ for now?

**Comment by sharkcz** [comment]
Yes, I think we can for now. Seems there was a problem with the rel-eng script that populates the primary mirror (https://dl.fedoraproject.org/pub/fedora-secondary/releases/32/Silverblue/). We should check that too.

**Comment by tpopela** [comment]
It's available in https://download.fedoraproject.org/pub/fedora/linux/releases/32/Silverblue/aarch64/iso/

**Comment by sharkcz** [comment]
I see now :-)

**Comment by sharkcz** [comment]
Awesome, LGTM

**Comment by runlevel5** [comment]
@tpopela please help review and merge this PR once it is good to go

**Pull request merged**
