### PR TITLE
Maintenance work after f37 release

### PR DESCRIPTION
**Pull request by kuba3351**
As usual, added F37 release announcement, and changed download links to point F37.

I found that there is no f37 compose for ppc64le on https://dl.fedoraproject.org/pub/fedora-secondary/releases/ so, I don't know if the download link will be ok when it will appear.

### CODE REVIEW

**Comment by tpopela** [comment]
Thank you @kuba3351 !!

**Comment by travier** [comment]
Thanks! The ppc64le links are broken. I've realized while updating the Kinoite sire as they are broken for Kinoite too.

**Comment by kuba3351** [comment]
It looks like the site was not refreshed after merge of this PR, can someone investigate it?

**Comment by travier** [comment]
I've realized that to. It's build somewhere into the Fedora infra.

**Pull request merged**
