### PR TITLE
Add Fedora 38 Announcement

### PR DESCRIPTION
**Pull request by Dvlv**
Added details about fedora 38.

### CODE REVIEW

**Comment by kuba3351** [comment]
I think it should contain info about Fedora Sericea spin release

**Comment by Dvlv** [comment]
Is that not a separate project, like Kinoite?

**Comment by Dvlv** [comment]
Nevermind, noticed the f35 announcement linked to Kinoite, so I've added a similar link to Sericea.

**Comment by travier** [comment]
LGTM. Let's also add a link to https://fedoramagazine.org/whats-new-fedora-38-workstation/ as it has nice screenshots?

**Comment by Dvlv** [comment]
Thanks @travier, added that link.

**Review by travier — APPROVED** [review]

**Pull request merged**
